name: Python package

on:
  push:
    branches:
      - main
      - feature/mean-function
  workflow_dispatch: {}

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: |
          python -m pip install --upgrade pip setuptools wheel twine
          pip install -e .
          pip install -r requirements.txt
      - run: pytest
      - run: python setup.py sdist bdist_wheel
      - name: Publish package to TestPyPI
        env:
          TWINE_USERNAME: ${{ secrets.TEST_PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD }}
        run: |
          python -m twine upload --repository-url https://test.pypi.org/legacy/ dist/*
