name: Publish Python Package to TestPyPI

on:
  push:
    branches:
      - main  # Ya da senin kullandığın ana branch adı

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # İstersen versiyonu değiştir

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine pytest

    - name: Run tests
      run: |
        pytest tests

    - name: Build package
      run: |
        python -m build

    - name: Publish to TestPyPI
      uses: pypa/gh-action-pypi-publish@v1.6.8
      with:
        user: __token__
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/project/sp211-21967646-98/