name: Python package

on:
  push:
    branches:
      - main
      - feature/mean-function
  pull_request:
    branches:
      - main
      - feature/mean-function

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel twine
          pip install -e .
          pip install -r requirements.txt

      - name: Run tests with pytest
        run: |
          pytest

      - name: Build package
        run: |
          python setup.py sdist bdist_wheel

      - name: Publish package to TestPyPI
        if: github.ref == 'refs/heads/feature/mean-function' || github.ref == 'refs/heads/main'
        env:
          TWINE_USERNAME: ${{ secrets.TEST_PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD }}
        run: |
          python -m twine upload --repository-url https://test.pypi.org/legacy/ dist/*
