name: Python package

on:
  push:
    branches:
      - main
      - feature/mean-function
  pull_request:
    branches:
      - main
      - feature/mean-function

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -e .  # editable install yapıyoruz ki paket import edilebilsin
          pip install -r requirements.txt  # varsa requirements dosyasını da yüklüyoruz

      - name: Run tests with pytest
        run: |
          pytest
